### ISSUE TITLE
withmock no run in windows?

### ISSUE THREAD

**Issue by Ronniexie** [qur/withmock#61] opened 2018-08-03 08:04 UTC
>withmock -debug go test
ERROR(pkg.GetImports): open /F_/WorkGit/Golang/Golang_Case/mock/test_mongo_mock/
controllers: The system cannot find the path specified.

**Comment by qur** [comment] 2018-08-03 22:00
Duplicate of #54

**Closed by qur** 2018-08-03 22:00 UTC
